# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Wireless network device drivers.
#

$(info mt76/6.12/Makefile: CONFIG_WLAN_VENDOR_MEDIATEK=$(CONFIG_WLAN_VENDOR_MEDIATEK))
$(info mt76/6.12/Makefile: CONFIG_MT76x0E=$(CONFIG_MT76x0E))

obj-$(CONFIG_WLAN_VENDOR_MEDIATEK) += mediatek/
