#!/bin/sh
set -e
# Copyright (C) 2002-2005 Flavio Stanchina
# Copyright (C) 2005-2006 Aric Cyr
# Copyright (C) 2007-2008 Mario Limonciello
# Copyright (C) 2009 Alberto Milone



CVERSION=`dpkg-query -W -f='${Version}' mt76xx-dkms | awk -F "-" '{print $1}' | cut -d\: -f2`
case "$1" in
    remove|upgrade)
		echo "Removing all mt76xx DKMS Modules"
		dkms remove -m mt76xx -v $CVERSION --all > /dev/null || true
		echo "Done."
        ;;
esac


